### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by Orange45** [mumax/mumax3-fft#1]
I am trying to install in mumax3 and when I run "go get github.com/mumax/mumax3-fft" it gives me these two errors that I'm not sure how to resolve:
go build github.com/barnex/fftw/internal/float: invalid flag in #cgo CFLAGS: -malign-double
go build github.com/barnex/fftw/internal/double: invalid flag in #cgo CFLAGS: -malign-double
Thanks in advance.

**Comment by chenminacm** [comment]
I came across the same problem too. Looking forward for help now.

**Comment by barnex** [comment]
Fixed at https://github.com/barnex/fftw/commit/b800f77a10deb839c7efdad45255d2fa01d32fcc
